CC=gcc
CFLAGS += -std=c11 -pedantic -g -Wall -Wextra -Wfloat-equal -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wcast-align -Wwrite-strings -Wconversion -Wunreachable-code

all: main 

main: main.o read_write.o



clean:
	rm -f *.o
	rm -f $(all)
	echo Clean done



